export const WORLD_SIZE = 10000;

export const SCALE_FACTOR = 4;

export const OVERLAY_WIDTH_PIXELS = SCALE_FACTOR * 780;

export const OVERLAY_WIDTH_HEIGHT = SCALE_FACTOR * 1040;

export const TILE_WIDTH_PIXELS = SCALE_FACTOR * 52;

export const OVERLAY_POSITION_X = WORLD_SIZE / 2 - OVERLAY_WIDTH_PIXELS / 2;

export const OVERLAY_POSITION_Y = WORLD_SIZE / 2 - OVERLAY_WIDTH_HEIGHT / 2;
